name: Download
version: "1.0.1"
developer: Erin Dalzell
commercial: true
description: Allow a file to be downloaded only once, or only if the user is logged in
url: https://silentzconsulting.com/addons/download
developer: Erin Dalzell
developer_url: https://silentzconsulting.com/addons
